### ISSUE TITLE
Option to permanently enable ads

### ISSUE THREAD

**Issue by gu3st** [yasp-dota/ui#11]
Another person popped in last night and suggested the ability for an option to permanently enable ads.

I think it'd be a good thing.

**Comment by howardchung** [comment]
I think it makes sense to either have ads on all the time or not have ads at all.  That said, we could make it a client-side option to show/hide ads so we don't need to touch the server at all.

**Comment by howardchung** [comment]
ads are honestly pretty ineffective--we are under $300 in ad revenue in the last month.

**Comment by howardchung** [comment]
I think if anything, we'll just disable the dynamic ads and leave them on all the time.
