### ISSUE TITLE
overview should be selected by default on routing tab

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/ui#38]
Also the base path should be /index, not /overview

**Comment by mike-robertson** [comment]
I actually changed it to overview but I can swap it back to index if you would like. I think overview is more descriptive though

**Comment by howardchung** [comment]
I'm fine with either.

**Comment by howardchung** [comment]
ex: https://ui.yasp.co/players/88367253 should have "overview" tab activated.

**Comment by mike-robertson** [comment]
should be resolved. Closing but reopen if you notice other bugs or open a new issue.

**Comment by howardchung** [comment]
Intentional reopen?

**Comment by mike-robertson** [comment]
Yea it won't be closed until we merge pr
