### ISSUE TITLE
"last played" text on player/heroes

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/ui#57]
Move column to leftmost after hero column.  Replace "last match" with "last played"

**Comment by mike-robertson** [comment]
Do you think that belongs there? The data is presorted by number of games, so it makes sense to display the number of games as the second column. I do agree this is separating the percentages which should be side by side ideally, maybe we should put this as the last column?

**Comment by howardchung** [comment]
Could try both and see what looks better.
