### ISSUE TITLE
Package.json needs to have dependencies properly sorted

### ISSUE THREAD

**Issue by mike-robertson** [yasp-dota/ui#69]
dependencies and devDependencies are 2 different things and they need to be separated. devDependencies are things that are required for dev/build process (webpack, webpack loaders etc.). dependencies are things which the application requires to run (react, react-dom, etc.).

**Comment by howardchung** [comment]
I'm not sure if it really matters.  Generally this is useful for libraries (where consumers don't need devDependencies usually), but probably no one is going to import this.

`npm install` installs both sets of dependencies.

End-users don't need to install at all, the packaged webpack bundle contains everything they need (so they don't actually need to npm install anything).

**Comment by mike-robertson** [comment]
That's true,  but I don't think we should do it like we are just because it won't break.
